# Generated by Django 5.2.3 on 2025-08-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
