# Generated by Django 5.2.3 on 2025-08-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_app', '0003_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='availability',
            field=models.CharField(blank=True, help_text='Availability of the volunteer (e.g., Weekends, Weekdays, Full-time)', max_length=50, null=True),
        ),
    ]
