# Generated by Django 5.2.3 on 2025-08-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_app', '0008_podcast_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField(help_text='Paste YouTube or Facebook video link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
