# Generated by Django 5.2.3 on 2025-08-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_app', '0009_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
