# Generated by Django 5.2.3 on 2025-08-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_app', '0012_eventphoto_newspapercutting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='reviews/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
