# Generated by Django 5.2.3 on 2025-09-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_app', '0014_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='created_by',
            new_name='user',
        ),
        migrations.AddField(
            model_name='campaign',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
